---
# This playbook deploys the whole application stack in this site.
- name: instalar cosas
  hosts: localhost
  remote_user: root
  roles:
    - { role: apache, when: '"apache" in roles.split(",")' }
    - { role: mysql, when: '"mysql" in roles.split(",")' }
    - { role: php, when: '"php" in roles.split(",")' }
    - { role: tomcat, when: '"tomcat" in roles.split(",")' }
