- name: Download Bosch Certificate File
  win_get_url:
    url: http://satellite.rh-sddc.test-bosch.com/pub/customer/Certificates/BOSCH-CA-DE.cer
    dest: C:\BOSCH-CA-DE.cer

- name: Add Bosch Certificate
  win_command: 'certutil.exe -addstore Root C:\BOSCH-CA-DE.cer'

# - name: Wait1
#   win_command: timeout 20 /NOBREAK

# - name: Delete Certificate File
#   win_file:
#     path: C:\BOSCH-CA-DE.cer
#     state: absent

- name: Download Bosch Certificate File1
  win_get_url:
    url: http://satellite.rh-sddc.test-bosch.com/pub/customer/Certificates/BOSCH-CA1-DE.cer
    dest: C:\BOSCH-CA1-DE.cer

# - name: Add Bosch Certificate1
#   win_command: 'certutil.exe -addstore Root C:\BOSCH-CA1-DE.cer'

# # - name: Wait2
# #   win_command: 'timeout 20 /NOBREAK'

# - name: Delete Certificate File1
#   win_file:
#     path: C:\BOSCH-CA1-DE.cer
#     state: absent

# For AeXNSC see:
# https://support.symantec.com/en_US/article.HOWTO1567.html

- name: Download AeXNSCHTTPs
  win_get_url:
    url: http://satellite.rh-sddc.test-bosch.com/pub/customer/Altiris_agent/AeXNSCHTTPs.exe
    dest: C:\AeXNSCHTTPs.exe

- name: Install AeXNSCHTTPs
  win_command: 'C:\AeXNSCHTTPs.exe /q /norestart /s'

# - name: Wait3
#   win_command: t'imeout 20 /NOBREAK'

- name: Delete AeXNSCHTTPs
  win_file:
    path: C:\AeXNSCHTTPs.exe
    state: absent

- name: Install SoftwareManagementSolution_Plugin_x64
  win_package:
    path: http://satellite.rh-sddc.test-bosch.com/pub/customer/Altiris_agent/SoftwareManagementSolution_Plugin_x64.msi
    product_id: '{F0A98DDC-4020-495D-B6B6-56C8F5BDA59D}'
    arguments: '/qn /norestart'
    state: present

# - name: Wait4
#   win_command: 'timeout 20 /NOBREAK'

- name: Install Symantec_InventoryAgent_x64
  win_package:
    path: http://satellite.rh-sddc.test-bosch.com/pub/customer/Altiris_agent/Symantec_InventoryAgent_x64.msi
    product_id: '{C0ACA929-1F04-4D2B-AB0C-9CBF8ABE1C60}'
    arguments: '/qn /norestart'
    state: present

# - name: Wait5
#   win_command: 'timeout 20 /NOBREAK'

- name: Install Symantec_ServerInventoryAgent_x64
  win_package:
    path: http://satellite.rh-sddc.test-bosch.com/pub/customer/Altiris_agent/Symantec_ServerInventoryAgent_x64.msi
    product_id: '{9BAF2D59-349A-4E61-88B5-97B1DE87FB6B}'
    arguments: '/qn /norestart'
    state: present

# - name: Wait6
#   win_command: timeout 30 /NOBREAK

# Here we need feedback from Bosch on why they have a Win64.msi file, and in their own env do use a x64.msi file.
# The Win64.msi file doesn't work, as we don't know the Product ID...
# And the MSIEXEC fails...

## - name: Download Altiris_PatchMgmtAgent_Win64.msi
##   win_get_url:
##     url: http://satellite.rh-sddc.test-bosch.com/pub/customer/Altiris_agent/Altiris_PatchMgmtAgent_Win64.msi
##     dest: C:\Altiris_PatchMgmtAgent_Win64.msi
## 
## - name: Install Altiris_PatchMgmtAgent_Win64.msi
##   win_command: 'msiexec /ia C:\Altiris_PatchMgmtAgent_Win64.msi'
## 
## - name: Delete Altiris_PatchMgmtAgent_Win64.msi
##   win_file:
##     path: C:\Altiris_PatchMgmtAgent_Win64.msi
##     state: absent

# - name: Install Altiris_PatchMgmtAgent_Win64
#   win_package:
#     path: http://satellite.rh-sddc.test-bosch.com/pub/customer/Altiris_agent/Altiris_PatchMgmtAgent_Win64.msi
# #    product_id: '{A1111111-1111-1111-1111-111111111111}'
#     product_id: '{92F2A534-C3E4-4B18-B3BD-329F5E848C8B}'
#     arguments: '/qn /norestart'
#     state: present

# - name: Wait7
#   win_command: timeout 60 /NOBREAK
