---
# This playbook deploys the whole application stack in this site.
- name: Trigguer list of roles sent from Service Dialog using extra_var roles
  hosts: all
  environment:
    ansible_host_key_checking: false
  remote_user: root
  gather_facts: false
  pre_tasks:
    - name: logging manageiq object
      debug: var=manageiq
      when: manageiq is defined

  roles:
    - { role: altiris, when: '"altiris" in rolescfme.split(",")' }
    - { role: sql, when: '"sql" in rolescfme.split(",")' }
    - { role: iis, when: '"iis" in rolescfme.split(",")' }
    - { role: ipconfig, when: '"ipconfig" in rolescfme.split(",")' }
    - { role: windows_update, when: '"windows_update" in rolescfme.split(",")' }
    - { role: managed, when: '"managed" in rolescfme.split(",")' }
    - { role: unmanaged, when: '"unmanaged" in rolescfme.split(",")' }
