---
- name: Do something on OpenStack with Ansible-Inside
  hosts: localhost
  connection: local
  environment:
    OS_CLIENT_CONFIG_FILE: /tmp/openstack.yaml

  tasks:
    - debug: var=manageiq
    - debug: var=manageiq.api_url
    - debug: var=manageiq.api_token
    - debug: var=manageiq.service
    - debug: var=os_ssl

    - name: Create OS_CLIENT_CONFIG_FILE for Non-SSL
      template:
        src: "{{ playbook_dir }}/../templates/openstack.yaml.j2"
        dest: /tmp/openstack.yaml
      when: os_ssl == "false"

    - name: Create OS_CLIENT_CONFIG_FILE for SSL
      template:
        src: "{{ playbook_dir }}/../templates/openstack.yaml.ssl.j2"
        dest: /tmp/openstack.yaml
      when: os_ssl == "true"

    # https://docs.ansible.com/ansible/os_auth_module.html
    - name: Authenticate to specified OpenStack provider
      os_auth:
        cloud: mycloud

    - name: Show service catalogue
      debug:
        var: service_catalog