---
- name: Do something on OpenStack with Ansible-Inside
  hosts: localhost
  connection: local
  environment:
    OS_CLIENT_CONFIG_FILE: /tmp/openstack.yaml

  vars:
    os_ssl: "{{ os_ssl | default('false') }}"

  tasks:
    - debug: var=instance_name
    # - debug: var=instance_flavour
    - debug: var=network_name
    - debug: var=os_ssl

    - name: Create OS_CLIENT_CONFIG_FILE for Non-SSL
      template:
        src: "{{ playbook_dir }}/../templates/openstack.yaml.j2"
        dest: /tmp/openstack.yaml
      when: os_ssl == "false"

    - name: Create OS_CLIENT_CONFIG_FILE for SSL
      template:
        src: "{{ playbook_dir }}/../templates/openstack.yaml.ssl.j2"
        dest: /tmp/openstack.yaml
      when: os_ssl == "true"

    # https://docs.ansible.com/ansible/os_auth_module.html
    - name: Authenticate to specified OpenStack provider
      os_auth:
        cloud: mycloud

    # https://docs.ansible.com/ansible/os_server_module.html
    - os_server:
        cloud: mycloud
        state: present
        name: "{{ instance_name }}"
        image: cirros
        # flavor: "{{ instance_flavour }}"
        flavor: tiny
        network: "{{ network_name }}"