---
- name: Do something on OpenStack with Ansible-Inside
  hosts: localhost
  connection: local

  tasks:
    - debug: var=network_name
    - debug: var=os_host
    - debug: var=os_user
    - debug: var=os_password

# https://docs.ansible.com/ansible/os_network_module.html
    - name: Add a network
      os_network:
        region_name: regionOne
        auth:
          username: "{{ os_user }}"
          password: "{{ os_password }}"
          project_name: admin
          domain_name: hailstorm
          auth_url: https://{{ os_host }}:13000/v3
        validate_certs: no
        state: present
        name: "{{ network_name }}"
        external: true
