---
- name: Do something on OpenStack with Ansible-Inside
  hosts: localhost
  connection: local
    
  tasks:
    - os_network:
       region_name: regionOne
       auth:
         username: admin
         password: 0pen_5ource
         project_name: demo-vms
         domain_name: hailstorm
         auth_url: https://openstack.rh-sddc.test-bosch.com:13000/v3
       validate_certs: no
       state: present
       name: mpfuetzntest
       external: true
