---
- name: Do something on OpenStack with Ansible-Inside
  hosts: localhost
  connection: local
  environment:
    OS_IDENTITY_API_VERSION: 3
    no_proxy: https://{{ os_host }}:13000/v3

  tasks:
    - debug: var=os_host
    - debug: var=os_user
    - debug: var=os_password
    - debug: var=os_project
    - debug: var=os_network_name

    - name: Add a network
      os_network:
        auth:
          auth_url: https://{{ os_host }}:13000/v3
          username: "{{os_user }}"
          password: "{{ os_password }}"
          project_name: "{{ os_project }}"
          domain_name: hailstorm
        validate_certs: no
        region_name: regionOne
        state: present
        name: "{{ os_network_name }}"
        project: "{{ os_project }}"
#        provider_network_type: 
#        provider_physical_network: 
#        provider_segmentation:id: 
        external: false
        shared: false

    - name: Create the test subnet
      os_subnet:
        auth:
          auth_url: https://{{ os_host }}:13000/v3
          username: "{{os_user }}"
          password: "{{ os_password }}"
          project_name: "{{ os_project }}"
          domain_name: hailstorm
        validate_certs: no
        region_name: regionOne
        state: present
        network_name: "{{ os_network_name }}"
        name: "{{ os_network_name + '_sub'}}"
        ip_version: 4
        cidr: 172.21.0.0/16
        gateway_ip: 172.21.0.1
        enable_dhcp: yes
        dns_nameservers:
          - 10.116.57.11
      when: os_network_name == "app-server"

    - name: Create the test subnet
      os_subnet:
        auth:
          auth_url: https://{{ os_host }}:13000/v3
          username: "{{os_user }}"
          password: "{{ os_password }}"
          project_name: "{{ os_project }}"
          domain_name: hailstorm
        validate_certs: no
        region_name: regionOne
        state: present
        network_name: "{{ os_network_name }}"
        name: "{{ os_network_name + '_sub'}}"
        ip_version: 4
        cidr: 172.22.0.0/16
        gateway_ip: 172.22.0.1
        enable_dhcp: yes
        dns_nameservers:
          - 10.116.57.11
      when: os_network_name == "db-server"

    - name: Create the test subnet
      os_subnet:
        auth:
          auth_url: https://{{ os_host }}:13000/v3
          username: "{{os_user }}"
          password: "{{ os_password }}"
          project_name: "{{ os_project }}"
          domain_name: hailstorm
        validate_certs: no
        region_name: regionOne
        state: present
        network_name: "{{ os_network_name }}"
        name: "{{ os_network_name + '_sub'}}"
        ip_version: 4
        cidr: 172.23.0.0/16
        gateway_ip: 172.23.0.1
        enable_dhcp: yes
        dns_nameservers:
          - 10.116.57.11
      when: os_network_name == "web-server"

    - name: Create the test router
      ignore_errors: yes #for some reasons, re-running this task gives errors
      os_router:
        auth:
          auth_url: https://{{ os_host }}:13000/v3
          username: "{{os_user }}"
          password: "{{ os_password }}"
          project_name: "{{ os_project }}"
          domain_name: hailstorm
        validate_certs: no
        region_name: regionOne
        state: present
        name: "{{ os_network_name + '_router' }}"
        network: guests
        external_fixed_ips:
          - subnet: sub_guests
        interfaces:
          - "{{ os_network_name + '_sub'}}"

    - name: Create a new security group
      os_security_group:
        auth:
          auth_url: https://{{ os_host }}:13000/v3
          username: "{{os_user }}"
          password: "{{ os_password }}"
          project_name: "{{ os_project }}"
          domain_name: hailstorm
        validate_certs: no
        region_name: regionOne
        state: present
        name: "{{ os_network_name }}"

    - name: Create a new security group allowing any ICMP
      os_security_group_rule:
        auth:
          auth_url: https://{{ os_host }}:13000/v3
          username: "{{os_user }}"
          password: "{{ os_password }}"
          project_name: "{{ os_project }}"
          domain_name: hailstorm
        validate_certs: no
        region_name: regionOne
        security_group: "{{ os_network_name }}"
        protocol: icmp
        remote_ip_prefix: 0.0.0.0/0

    - name: Create a new security group allowing any SSH connection
      os_security_group_rule:
        auth:
          auth_url: https://{{ os_host }}:13000/v3
          username: "{{os_user }}"
          password: "{{ os_password }}"
          project_name: "{{ os_project }}"
          domain_name: hailstorm
        validate_certs: no
        region_name: regionOne
        security_group: "{{ os_network_name }}"
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
        remote_ip_prefix: 0.0.0.0/0

    - name: Create a new security group allowing any RDP connection
      os_security_group_rule:
        auth:
          auth_url: https://{{ os_host }}:13000/v3
          username: "{{os_user }}"
          password: "{{ os_password }}"
          project_name: "{{ os_project }}"
          domain_name: hailstorm
        validate_certs: no
        region_name: regionOne
        security_group: "{{ os_network_name }}"
        protocol: tcp
        port_range_min: 3389
        port_range_max: 3389
        remote_ip_prefix: 0.0.0.0/0

    - name: Create a new security group allowing any Ansible connection
      os_security_group_rule:
        auth:
          auth_url: https://{{ os_host }}:13000/v3
          username: "{{os_user }}"
          password: "{{ os_password }}"
          project_name: "{{ os_project }}"
          domain_name: hailstorm
        validate_certs: no
        region_name: regionOne
        security_group: "{{ os_network_name }}"
        protocol: tcp
        port_range_min: 5986
        port_range_max: 5986
        remote_ip_prefix: 0.0.0.0/0

